'use client';

interface SolutionModalProps {
  level: number;
  onConfirm: () => void;
  onCancel: () => void;
}

export default function SolutionModal({ level, onConfirm, onCancel }: SolutionModalProps) {
  return (
    <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center animate-fade-in" onClick={onCancel}>
      <div className="bg-surface-1 border border-border p-6 max-w-sm w-full mx-4 shadow-xl animate-slide-up" onClick={e => e.stopPropagation()}>
        <h3 className="text-sm font-semibold text-white mb-2">View Reference Solution</h3>
        <p className="text-xs text-[#aaa] leading-relaxed mb-3">
          We recommend trying to solve Level {level} on your own first. Working through the problem builds the muscle memory you need in a real interview.
        </p>
        <p className="text-xs text-[#aaa] leading-relaxed mb-3">
          If you&apos;re stuck, seeing a reference solution can help you learn the pattern. This will replace your current code.
        </p>
        <p className="text-xs text-[#666] leading-relaxed mb-4">
          Note: This solution was generated by Claude. There are many valid approaches, and yours may differ.
        </p>
        <div className="flex justify-end gap-2">
          <button onClick={onCancel} className="px-3 py-1.5 text-xs font-medium text-[#aaa] bg-surface-2 border border-border hover:bg-surface-3 transition-colors">
            Cancel
          </button>
          <button onClick={onConfirm} className="px-3 py-1.5 text-xs font-semibold text-white bg-accent hover:bg-accent/80 transition-colors">
            Load Solution
          </button>
        </div>
      </div>
    </div>
  );
}
